name = "qvSZP"
version = "2.2.0"
license = "license"
author = ["Marcel Mueller", "Thomas Froitzheim", "Stefan Grimme"]
maintainer = "marcel.mueller@thch.uni-bonn.de"
copyright = "Copyright 2023-2024, Marcel Mueller"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link=["lapack"]

[install]
library = false

[dependencies]
tblite.git = "https://github.com/tblite/tblite"
stdlib = "*"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
mstore.git = "https://github.com/grimme-lab/mstore"
